name: Function CI/CD
run-name: ${{ github.actor }} is testing out Azure Function GitHub Actions 🚀

on:
  push:
    branches:
      - main
      - '!feature/**'
    paths:
      - 'src/AzureFunction/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - main
      - '!feature/**'
    paths:
      - 'src/AzureFunction/**'

env:
  imageName: apim-food-app
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/AzureFunction/DEPLOY.BikeApp.Function/'

jobs:
  build:
    environment: lab
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore src/AzureFunction/DEPLOY.BikeApp.Function/DEPLOY.BikeApp.Function.csproj

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          # pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          # pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          # ls
          popd

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: deploy-function-app
        with:
          app-name: 'func-apim-bike-app' # -lab
          slot-name: 'production'
          publish-profile: ${{ secrets.FUNCTION_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Set Web App ACR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: app-apim-bike-app #-lab
          app-settings-json: |
            [
                {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "Development",
                    "slotSetting": false
                }
            ]
