name: Function CI/CD
run-name: ${{ github.actor }} is testing out Azure Function GitHub Actions 🚀

on:
  push:
    branches:
      - main
      - '!feature/**'
    paths:
      - 'src/AzureFunction/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  pull_request:
    branches:
      - main
      - '!feature/**'
    paths:
      - 'src/AzureFunction/**'

env:
  imageName: apim-food-app
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/AzureFunction/DEPLOY.BikeApp.API'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x', '8.0.x']
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    outputs:
      imageTag: ${{ steps.get-version.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore src/AzureFunction/DEPLOY.BikeApp.API/DEPLOY.BikeApp.API.csproj

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Build and push Docker image
        uses: docker/login-action@v3.3.0
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get-Version from csproj
        id: get-version
        shell: bash
        run: |
          version=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' ./src/AzureFunction/DEPLOY.BikeApp.API/DEPLOY.BikeApp.API.csproj)
          echo "tag=$version" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        run: |
          docker buildx build -f ./src/AzureFunction/DEPLOY.BikeApp.API/Dockerfile -t ${{ github.actor }}/${{ env.imageName }}:${{ steps.get-version.outputs.tag }} ./src/AzureFunction
          docker tag ${{ github.actor }}/${{ env.imageName }}:${{ steps.get-version.outputs.tag }} ${{ github.actor }}/${{ env.imageName }}:latest
          docker push ${{ github.actor }}/${{ env.imageName }}:${{ steps.get-version.outputs.tag }}
          docker push ${{ github.actor }}/${{ env.imageName }}:latest

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Log in to Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'func-apim-food-app-lab'
          slot-name: 'production'
          publish-profile: ${{ secrets.FUNCTION_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Set Web App ACR authentication
        uses: Azure/appservice-settings@v1
        with:
          app-name: app-apim-bike-app-lab
          app-settings-json: |
            [
                {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "Development",
                    "slotSetting": false
                }
            ]
